// Normalized names of Trainer "Item", "Stadium", and "Pokémon Tool" cards
// (794 from the modern API + 12 vintage Item trainers the API can't tag = 806 unique
// names). The `cards` table has no card-type column, so these card types are excluded
// from the comparison pool BY NAME.
//
// Generated from the Pokemon TCG API (api.pokemontcg.io):
//   q=supertype:Trainer subtypes:"<Item | Stadium | Pokémon Tool>"
// Names are normalized: NFKD, drop non-ASCII, lowercase, non-alphanumerics
// to spaces, collapse — must match normalizeName() in api/comparison/next.
// Regenerate when new sets add such trainers. Supporters are NOT here.
//
// CAVEAT — pre-2013 trainers predate the Item/Stadium/Tool subtypes, so in the API they
// are supertype:Trainer with NO subtype and the query above misses them. Any that are
// rarity Rare/Rare Holo then slip through the "keep vintage Rares" path in the route
// (e.g. PokéGear, Neo Genesis 88/111). The 12 vintage Item trainers below were added by
// hand to close that leak; the vintage Gym-Leader/character cards (Misty, Blaine, Lass…)
// are the era's Supporter analog and are deliberately KEPT, like modern Supporters.
export const EXCLUDED_TRAINER_NAMES = new Set<string>([
  "academy at night",
  "accompanying flute",
  "acro bike",
  "adventure bag",
  "adversity policy",
  "aerodactyl spirit link",
  "aether paradise conservation area",
  "aggron spirit link",
  "air balloon",
  "alakazam spirit link",
  "all night party",
  "alph lithograph",
  "altar of the moone",
  "altar of the sunne",
  "altaria spirit link",
  "ampharos spirit link",
  "amulet coin",
  "amulet of hope",
  "ancient booster energy capsule",
  "ancient crystal",
  "ancient ruins",
  "ancient tomb",
  "ange floette",
  "antique cover fossil",
  "antique dome fossil",
  "antique helix fossil",
  "antique jaw fossil",
  "antique old amber",
  "antique plume fossil",
  "antique root fossil",
  "antique sail fossil",
  "apricorn forest",
  "aqua diffuser",
  "aqua patch",
  "arc phone",
  "arcade game",
  "area zero underdepths",
  "armor fossil",
  "armor fossil shieldon",
  "artazon",
  "arven s sandwich",
  "aspertia city gym",
  "assault vest",
  "audino spirit link",
  "awakening drum",
  "babiri berry",
  "balloon berry",
  "battle cage",
  "battle city",
  "battle compressor team flare gear",
  "battle frontier",
  "battle tower",
  "battle vip pass",
  "beach court",
  "beast ball",
  "beast bringer",
  "beast ring",
  "beastite",
  "beedrill spirit link",
  "beginning door",
  "bench shield",
  "bent spoon",
  "berry",
  "bicycle",
  "big air balloon",
  "big charm",
  "big malasada",
  "big parasol",
  "billowing smoke",
  "binding mochi",
  "black market",
  "blastoise spirit link",
  "blizzard town",
  "blowtorch",
  "blunder policy",
  "bodybuilding dumbbells",
  "boost shake",
  "box of disaster",
  "boxed order",
  "brave bangle",
  "bravery charm",
  "brilliant blender",
  "brock s pewter city gym",
  "broken ground gym",
  "broken time space",
  "brooklet hill",
  "bubble coat",
  "buddy buddy poffin",
  "buddy buddy rescue",
  "buff padding",
  "buffer piece",
  "bug catching set",
  "burned tower",
  "burning scarf",
  "bursting balloon",
  "calamitous snowy mountain",
  "calamitous wasteland",
  "call bell",
  "camerupt spirit link",
  "camping gear",
  "canceling cologne",
  "capacious bucket",
  "cape of toughness",
  "captivating poke puff",
  "capturing aroma",
  "celadon city gym",
  "cerulean city gym",
  "cessation crystal",
  "champion s room",
  "champions festival",
  "championship arena",
  "chaos gym",
  "chaos tower",
  "chaotic swell",
  "charizard spirit link",
  "cherish ball",
  "chill teaser toy",
  "chip chip ice axe",
  "choice band",
  "choice belt",
  "choice helmet",
  "cinnabar city gym",
  "circhester bath",
  "claw fossil",
  "claw fossil anorith",
  "cleansing gloves",
  "clefairy doll",
  "colbur berry",
  "collapsed stadium",
  "colress machine",
  "community center",
  "computer search",
  "conductive quarry",
  "core memory",
  "counter catcher",
  "counter gain",
  "counterattack claws",
  "cover fossil",
  "cram o matic",
  "cross switcher",
  "crossceiver",
  "crushing gloves",
  "crushing hammer",
  "crystal beach",
  "crystal cave",
  "crystal edge",
  "crystal shard",
  "crystal wall",
  "curse powder",
  "cursed duster",
  "cursed shovel",
  "cursed stone",
  "custom catcher",
  "cycling road",
  "cynthia s power weight",
  "damage mover",
  "damage pump",
  "dangerous drill",
  "dangerous laser",
  "dark city",
  "dark claw",
  "dark patch",
  "dashing pouch",
  "dawn stadium",
  "deduction kit",
  "defender",
  "defiance band",
  "defiance vest",
  "delivery drone",
  "deluxe bomb",
  "desert ruins",
  "devolution spray",
  "devolution spray z",
  "devoured field",
  "digging gloves",
  "dimension valley",
  "dive ball",
  "dizzying valley",
  "dome fossil",
  "dome fossil kabuto",
  "double full heal",
  "dowsing machine",
  "dragon elixir",
  "dragon talon",
  "dragonium z dragon claw",
  "drake s stadium",
  "dream ball",
  "drone rotom",
  "dual ball",
  "dusk ball",
  "dusk stone",
  "dust island",
  "dyna tree hill",
  "ear ringing bell",
  "earthen seal stone",
  "earthen vessel",
  "echoing horn",
  "eco arm",
  "ecogym",
  "egg incubator",
  "electric generator",
  "electric memory",
  "electrocharger",
  "electromagnetic radar",
  "electropower",
  "elemental badge",
  "emergency jelly",
  "eneporter",
  "energy charge",
  "energy coin",
  "energy exchanger",
  "energy link",
  "energy loto",
  "energy pickup",
  "energy pouch",
  "energy recycle system",
  "energy recycler",
  "energy removal 2",
  "energy reset",
  "energy restore",
  "energy retrieval",
  "energy returner",
  "energy root",
  "energy search",
  "energy search pro",
  "energy spinner",
  "energy stadium",
  "energy sticker",
  "energy swatter",
  "energy switch",
  "enhanced hammer",
  "escape board",
  "escape rope",
  "ether",
  "eviolite",
  "evolution incense",
  "evosoda",
  "exp all",
  "exp share",
  "expedition uniform",
  "expert belt",
  "faded town",
  "fairy charm ability",
  "fairy charm dragon",
  "fairy charm fighting",
  "fairy charm grass",
  "fairy charm lightning",
  "fairy charm psychic",
  "fairy charm ub",
  "fairy drop",
  "fairy garden",
  "familiar bell",
  "fan of waves",
  "farewell bell",
  "feather ball",
  "festival grounds",
  "field blower",
  "fiery flint",
  "fiery torch",
  "fighting au lait",
  "fighting fury belt",
  "fighting gong",
  "fighting memory",
  "fighting stadium",
  "fire crystal",
  "fire memory",
  "fire resistant gloves",
  "first ticket",
  "float stone",
  "floral crown",
  "fluffy berry",
  "flyinium z air slash",
  "focus band",
  "focus sash",
  "fog crystal",
  "forest of giant plants",
  "forest of vitality",
  "forest seal stone",
  "fossil excavation kit",
  "fossil excavation map",
  "fresh water set",
  "friend ball",
  "frozen city",
  "fuchsia city gym",
  "full face guard",
  "full flame",
  "full heal",
  "full metal lab",
  "future booster energy capsule",
  "g booster",
  "g scope",
  "galactic hq",
  "galar mine",
  "galarian chestplate",
  "gallade spirit link",
  "gapejaw bog",
  "garchomp spirit link",
  "gardevoir spirit link",
  "gengar spirit link",
  "giant bomb",
  "giant cape",
  "giant hearth",
  "giant stump",
  "glacia s stadium",
  "glalie spirit link",
  "glass trumpet",
  "glimwood tangle",
  "gold berry",
  "gold potion",
  "good rod",
  "grabber",
  "grand tree",
  "granite cave",
  "grass memory",
  "gravity gemstone",
  "gravity mountain",
  "great ball",
  "great catcher",
  "great haul net",
  "great potion",
  "greedy dice",
  "groudon spirit link",
  "gutsy pickaxe",
  "gyarados spirit link",
  "gym badge",
  "haban berry",
  "hand scope",
  "hand trimmer",
  "handheld fan",
  "hard charm",
  "head ringer team flare hyper gear",
  "healing berry",
  "healing field",
  "healing scarf",
  "heat factory",
  "heavy ball",
  "heavy baton",
  "heavy boots",
  "helix fossil",
  "helix fossil omanyte",
  "here comes team rocket",
  "hero s cape",
  "hero s medal",
  "high pressure system",
  "hisuian heavy ball",
  "hole digging shovel",
  "holon circle",
  "holon fossil",
  "holon lake",
  "holon legacy",
  "holon research tower",
  "holon ruins",
  "holon transceiver",
  "hop s bag",
  "hop s choice band",
  "houndoom spirit link",
  "hunting gloves",
  "hustle belt",
  "hyper aroma",
  "hyper potion",
  "hypnotoxic laser",
  "indigo plateau",
  "iron defender",
  "island cave",
  "island challenge amulet",
  "item finder",
  "jamming net team flare hyper gear",
  "jamming tower",
  "jaw fossil",
  "jubilife village",
  "judge whistle",
  "jumbo ice cream",
  "junk arm",
  "justified gloves",
  "karate belt",
  "kyogre spirit link",
  "lake acuity",
  "lake boundary",
  "lana s fishing rod",
  "last chance potion",
  "latios spirit link",
  "lavender town",
  "leafy camo poncho",
  "leftovers",
  "legend box",
  "letter of encouragement",
  "level ball",
  "level max",
  "levincia",
  "life dew",
  "life forest",
  "life herb",
  "light ball",
  "lillie s pearl",
  "lillie s poke doll",
  "lively stadium",
  "looker whistle",
  "lost blender",
  "lost city",
  "lost remover",
  "lost vacuum",
  "lost world",
  "love ball",
  "low pressure system",
  "lucario spirit link",
  "lucky egg",
  "lucky helmet",
  "lucky ice pop",
  "lucky stadium",
  "lum berry",
  "lumiose city",
  "lumiose galette",
  "lure ball",
  "lure module",
  "luxurious cape",
  "luxury ball",
  "lysandre labs",
  "magma basin",
  "magma pointer",
  "magnetic storm",
  "maintenance",
  "manectric spirit link",
  "martial arts dojo",
  "master ball",
  "mawile spirit link",
  "max elixir",
  "max potion",
  "max revive",
  "max rod",
  "maximum belt",
  "meddling memo",
  "mega catcher",
  "mega signal",
  "mega turbo",
  "megaton blower",
  "memory berry",
  "memory capsule",
  "mesagoza",
  "metal core barrier",
  "metal frying pan",
  "metal goggles",
  "metal saucer",
  "meteor falls",
  "mewtwo spirit link",
  "miasma valley",
  "miracle berry",
  "miracle headset",
  "mirage gate",
  "mirage stadium",
  "missing clover",
  "misty s cerulean city gym",
  "mixed herbs",
  "moomoo cheese",
  "moomoo milk",
  "moon sun badge",
  "moonlight stadium",
  "moonlit hill",
  "mount lanakila",
  "mountain ring",
  "mt coronet",
  "mt moon",
  "multi switch",
  "muscle band",
  "mysterious fossil",
  "mysterious shard",
  "mysterious treasure",
  "mystery garden",
  "mystery zone",
  "n s castle",
  "n s pp up",
  "narrow gym",
  "nemona s backpack",
  "nest ball",
  "net ball",
  "neutralization zone",
  "night maintenance",
  "night pokemon center",
  "night stretcher",
  "night teleporter",
  "nighttime mine",
  "no removal gym",
  "normalium z tackle",
  "nugget",
  "occa berry",
  "ogre s mask",
  "old amber",
  "old amber aerodactyl",
  "old cemetery",
  "old pc",
  "old rod",
  "oran berry",
  "order pad",
  "ordinary rod",
  "paint roller",
  "pal pad",
  "panic mask",
  "paradise resort",
  "parallel city",
  "passho berry",
  "path to the peak",
  "patrol cap",
  "payapa berry",
  "peeking red card",
  "perilous jungle",
  "pewter city gym",
  "phoebe s stadium",
  "picnic basket",
  "pidgeot spirit link",
  "plasma frigate",
  "plume fossil",
  "pluspower",
  "po town",
  "poison barb",
  "poke ball",
  "poke blower",
  "poke drawer",
  "poke healer",
  "poke pad",
  "poke radar",
  "poke vital a",
  "pokedex",
  "pokedex handy909",
  "pokedex handy910is",
  "pokegear",
  "pokegear 3 0",
  "pokemon breeder",
  "pokemon catcher",
  "pokemon center",
  "pokemon circulator",
  "pokemon communication",
  "pokemon contest hall",
  "pokemon league headquarters",
  "pokemon park",
  "pokemon rescue",
  "pokemon research lab",
  "pokemon reversal",
  "pokemon tower",
  "pokemon trader",
  "pokenav",
  "pokestop",
  "postwick",
  "pot helmet",
  "potion",
  "power memory",
  "power plant",
  "power tablet",
  "power tree",
  "powerglass",
  "practice studio",
  "precious trolley",
  "premier ball",
  "premium power pro",
  "prime catcher",
  "primordial altar",
  "prism tower",
  "professor s letter",
  "protection cube",
  "protective goggles",
  "protective orb",
  "psychic memory",
  "punk helmet",
  "puzzle of time",
  "quad stone",
  "quick ball",
  "radio tower",
  "rainbow brush",
  "random receiver",
  "rapid strike scroll of swirls",
  "rapid strike scroll of the flying dragon",
  "rapid strike scroll of the skies",
  "rare candy",
  "rare fossil",
  "rayquaza spirit link",
  "reboot pod",
  "recycle",
  "red card",
  "redeemable ticket",
  "repeat ball",
  "repel",
  "rescue board",
  "rescue carrier",
  "rescue scarf",
  "rescue stretcher",
  "research record",
  "reserved ticket",
  "reset stamp",
  "resistance gym",
  "return label",
  "reversal trigger",
  "reverse valley",
  "revitalizer",
  "revive",
  "ribbon badge",
  "rigid band",
  "risky ruins",
  "robo substitute team flare gear",
  "rock chestplate",
  "rock guard",
  "rocket s hideout",
  "rocket s minefield gym",
  "rocket s poke ball",
  "rocket s tricky gym",
  "rocky helmet",
  "roller skates",
  "root fossil",
  "root fossil lileep",
  "rose tower",
  "roto stick",
  "rotom bike",
  "rotom dex",
  "rotom dex poke finder mode",
  "rotom phone",
  "rough seas",
  "rubber gloves",
  "rugged helmet",
  "ruins of alph",
  "rusted shield",
  "rusted sword",
  "sacred ash",
  "sacred charm",
  "saffron city gym",
  "sail fossil",
  "salamence spirit link",
  "sceptile spirit link",
  "scizor spirit link",
  "scoop up",
  "scoop up cyclone",
  "scoop up net",
  "scorched earth",
  "scramble switch",
  "sea of nothingness",
  "secret box",
  "shadow circle",
  "sharpedo spirit link",
  "shopping center",
  "shrine of memories",
  "shrine of punishment",
  "sidney s stadium",
  "silent lab",
  "silver bangle",
  "silver mirror",
  "single strike scroll of piercing",
  "single strike scroll of scorn",
  "single strike scroll of the fanged dragon",
  "sitrus berry",
  "skaters park",
  "skull fossil",
  "sky field",
  "sky pillar",
  "sky seal stone",
  "skyarrow bridge",
  "slowbro spirit link",
  "slumbering forest",
  "snorlax doll",
  "snow leaf badge",
  "snowpoint temple",
  "solid rage",
  "space center",
  "sparkling crystal",
  "sparkling robe",
  "special charge",
  "special red card",
  "speed stadium",
  "spell tag",
  "spicy seasoned curry",
  "spikemuth",
  "spikemuth gym",
  "spirit mask",
  "spongy gloves",
  "sprout tower",
  "stadium nav",
  "star piece",
  "stark mountain",
  "startling megaphone",
  "stealthy hood",
  "steel shelter",
  "steelix spirit link",
  "stormy mountains",
  "strange cave",
  "strange timepiece",
  "strength charm",
  "struggle gloves",
  "sunyshore city gym",
  "super energy removal",
  "super energy retrieval",
  "super potion",
  "super rod",
  "super scoop up",
  "supereffective glasses",
  "superior energy retrieval",
  "surfing beach",
  "surprise box",
  "survival brace",
  "suspicious food tin",
  "sweet honey",
  "switch",
  "switch cart",
  "switch raft",
  "switching cups",
  "tag call",
  "tag switch",
  "target whistle team flare gear",
  "team aqua ball",
  "team aqua belt",
  "team aqua hideout",
  "team aqua s great ball",
  "team aqua s secret base",
  "team galactic s invention g 101 energy gain",
  "team galactic s invention g 103 power spray",
  "team galactic s invention g 105 poke turn",
  "team galactic s invention g 109 sp radar",
  "team magma ball",
  "team magma belt",
  "team magma hideout",
  "team magma s great ball",
  "team magma s secret base",
  "team plasma badge",
  "team plasma ball",
  "team rocket s bother bot",
  "team rocket s factory",
  "team rocket s great ball",
  "team rocket s hypnotizer",
  "team rocket s transceiver",
  "team rocket s venture bomb",
  "team rocket s watchtower",
  "team yell towel",
  "technical machine blindside",
  "technical machine crisis punch",
  "technical machine devolution",
  "technical machine evolution",
  "technical machine fluorite",
  "technical machine turbo energize",
  "techno radar",
  "telescopic sight",
  "temple of sinnoh",
  "tera orb",
  "the rocket s training gym",
  "thick scale",
  "thought wave machine",
  "thunder mountain",
  "time capsule",
  "time shard",
  "time space distortion",
  "timer ball",
  "tm machine",
  "tool box",
  "tool jammer",
  "tool retriever",
  "tool scrapper",
  "tormenting spray",
  "tower of darkness",
  "tower of waters",
  "town map",
  "town store",
  "toy catcher",
  "trainers mail",
  "training center",
  "training court",
  "transformation tome",
  "treasure tracker",
  "trekking shoes",
  "trick coin",
  "trick shovel",
  "tropical beach",
  "tropical tidal wave",
  "tropical wind",
  "turbo patch",
  "turffield stadium",
  "twist mountain",
  "tyranitar spirit link",
  "u turn board",
  "ultimate zone",
  "ultra ball",
  "ultra space",
  "underground lake",
  "undersea ruins",
  "unfair stamp",
  "unidentified fossil",
  "urn of vitality",
  "vengeful punch",
  "venusaur spirit link",
  "vermilion city gym",
  "victory cup",
  "victory piece",
  "virbank city gym",
  "viridian city gym",
  "viridian forest",
  "vitality band",
  "vs seeker",
  "wait and see hammer",
  "wait and see turbo",
  "warp point",
  "water memory",
  "weakness policy",
  "weeding gloves",
  "wela volcano park",
  "welcoming lantern",
  "wide lens",
  "windstorm",
  "windup arm",
  "wishful baton",
  "wondrous labyrinth",
  "wondrous patch",
  "wyndon stadium",
  "xtransceiver",
  "yell horn",
]);
