// Normalized names of Trainer "Item" and "Stadium" cards (368 Item + 205
// Stadium = 573 names). The `cards` table has no card-type column, so these
// card types are excluded from the comparison pool BY NAME.
//
// Generated from the Pokemon TCG API (api.pokemontcg.io):
//   q=supertype:Trainer subtypes:Item   and   subtypes:Stadium
// Names are normalized: NFKD, drop non-ASCII, lowercase, non-alphanumerics
// to spaces, collapse — must match normalizeName() in api/comparison/next.
// Regenerate when new sets add Items/Stadiums. Supporters/Tools are NOT here.
export const ITEM_STADIUM_NAMES = new Set<string>([
  "academy at night",
  "accompanying flute",
  "acro bike",
  "adventure bag",
  "aether paradise conservation area",
  "all night party",
  "alph lithograph",
  "altar of the moone",
  "altar of the sunne",
  "ancient ruins",
  "ancient tomb",
  "ange floette",
  "antique cover fossil",
  "antique dome fossil",
  "antique helix fossil",
  "antique jaw fossil",
  "antique old amber",
  "antique plume fossil",
  "antique root fossil",
  "antique sail fossil",
  "apricorn forest",
  "aqua patch",
  "arc phone",
  "area zero underdepths",
  "armor fossil",
  "armor fossil shieldon",
  "artazon",
  "arven s sandwich",
  "aspertia city gym",
  "awakening drum",
  "battle cage",
  "battle city",
  "battle compressor team flare gear",
  "battle frontier",
  "battle tower",
  "battle vip pass",
  "beach court",
  "beast ball",
  "beast ring",
  "beginning door",
  "bicycle",
  "big malasada",
  "black market",
  "blizzard town",
  "blowtorch",
  "blunder policy",
  "boost shake",
  "box of disaster",
  "boxed order",
  "brilliant blender",
  "brock s pewter city gym",
  "broken ground gym",
  "broken time space",
  "brooklet hill",
  "buddy buddy poffin",
  "buddy buddy rescue",
  "bug catching set",
  "burned tower",
  "calamitous snowy mountain",
  "calamitous wasteland",
  "call bell",
  "camping gear",
  "canceling cologne",
  "capacious bucket",
  "captivating poke puff",
  "capturing aroma",
  "celadon city gym",
  "cerulean city gym",
  "champion s room",
  "champions festival",
  "championship arena",
  "chaos gym",
  "chaos tower",
  "chaotic swell",
  "cherish ball",
  "chill teaser toy",
  "chip chip ice axe",
  "choice belt",
  "cinnabar city gym",
  "circhester bath",
  "claw fossil",
  "claw fossil anorith",
  "cleansing gloves",
  "collapsed stadium",
  "colress machine",
  "community center",
  "computer search",
  "conductive quarry",
  "counter catcher",
  "cover fossil",
  "cram o matic",
  "cross switcher",
  "crossceiver",
  "crushing hammer",
  "crystal beach",
  "crystal cave",
  "cursed stone",
  "custom catcher",
  "cycling road",
  "damage mover",
  "damage pump",
  "dangerous drill",
  "dangerous laser",
  "dark city",
  "dark patch",
  "dawn stadium",
  "deduction kit",
  "defender",
  "delivery drone",
  "desert ruins",
  "devolution spray",
  "devolution spray z",
  "devoured field",
  "digging gloves",
  "dimension valley",
  "dive ball",
  "dizzying valley",
  "dome fossil",
  "dome fossil kabuto",
  "double full heal",
  "dowsing machine",
  "dragon elixir",
  "drake s stadium",
  "dream ball",
  "drone rotom",
  "dual ball",
  "dusk ball",
  "dusk stone",
  "dust island",
  "dyna tree hill",
  "earthen seal stone",
  "earthen vessel",
  "echoing horn",
  "eco arm",
  "ecogym",
  "egg incubator",
  "electric generator",
  "electrocharger",
  "electromagnetic radar",
  "electropower",
  "elemental badge",
  "emergency jelly",
  "eneporter",
  "energy charge",
  "energy coin",
  "energy exchanger",
  "energy loto",
  "energy pickup",
  "energy recycle system",
  "energy recycler",
  "energy removal 2",
  "energy reset",
  "energy restore",
  "energy retrieval",
  "energy returner",
  "energy search",
  "energy search pro",
  "energy spinner",
  "energy stadium",
  "energy sticker",
  "energy swatter",
  "energy switch",
  "enhanced hammer",
  "escape rope",
  "ether",
  "evolution incense",
  "evosoda",
  "expedition uniform",
  "faded town",
  "fairy drop",
  "fairy garden",
  "familiar bell",
  "fan of waves",
  "farewell bell",
  "feather ball",
  "festival grounds",
  "field blower",
  "fiery flint",
  "fiery torch",
  "fighting au lait",
  "fighting gong",
  "fighting stadium",
  "fire crystal",
  "first ticket",
  "fog crystal",
  "forest of giant plants",
  "forest of vitality",
  "forest seal stone",
  "fossil excavation kit",
  "fossil excavation map",
  "fresh water set",
  "friend ball",
  "frozen city",
  "fuchsia city gym",
  "full face guard",
  "full flame",
  "full heal",
  "full metal lab",
  "galactic hq",
  "galar mine",
  "gapejaw bog",
  "giant hearth",
  "giant stump",
  "glacia s stadium",
  "glass trumpet",
  "glimwood tangle",
  "gold potion",
  "good rod",
  "grabber",
  "grand tree",
  "granite cave",
  "gravity mountain",
  "great ball",
  "great catcher",
  "great haul net",
  "great potion",
  "greedy dice",
  "gutsy pickaxe",
  "gym badge",
  "hand scope",
  "hand trimmer",
  "healing field",
  "heat factory",
  "heavy ball",
  "helix fossil",
  "helix fossil omanyte",
  "high pressure system",
  "hisuian heavy ball",
  "hole digging shovel",
  "holon circle",
  "holon fossil",
  "holon lake",
  "holon legacy",
  "holon research tower",
  "holon ruins",
  "holon transceiver",
  "hop s bag",
  "hunting gloves",
  "hyper aroma",
  "hyper potion",
  "hypnotoxic laser",
  "indigo plateau",
  "iron defender",
  "island cave",
  "jamming tower",
  "jaw fossil",
  "jubilife village",
  "judge whistle",
  "jumbo ice cream",
  "junk arm",
  "lake acuity",
  "lake boundary",
  "lana s fishing rod",
  "last chance potion",
  "lavender town",
  "leafy camo poncho",
  "legend box",
  "letter of encouragement",
  "level ball",
  "level max",
  "levincia",
  "life forest",
  "life herb",
  "lillie s poke doll",
  "lively stadium",
  "looker whistle",
  "lost blender",
  "lost city",
  "lost remover",
  "lost vacuum",
  "lost world",
  "love ball",
  "low pressure system",
  "lucky ice pop",
  "lucky stadium",
  "lumiose city",
  "lumiose galette",
  "lure ball",
  "lure module",
  "luxury ball",
  "lysandre labs",
  "magma basin",
  "magnetic storm",
  "maintenance",
  "martial arts dojo",
  "master ball",
  "max elixir",
  "max potion",
  "max revive",
  "max rod",
  "meddling memo",
  "mega catcher",
  "mega signal",
  "mega turbo",
  "megaton blower",
  "mesagoza",
  "metal saucer",
  "meteor falls",
  "miasma valley",
  "miracle headset",
  "mirage gate",
  "mirage stadium",
  "missing clover",
  "misty s cerulean city gym",
  "mixed herbs",
  "moomoo cheese",
  "moomoo milk",
  "moon sun badge",
  "moonlight stadium",
  "moonlit hill",
  "mount lanakila",
  "mountain ring",
  "mt coronet",
  "mt moon",
  "multi switch",
  "mysterious fossil",
  "mysterious treasure",
  "mystery garden",
  "mystery zone",
  "n s castle",
  "n s pp up",
  "narrow gym",
  "nemona s backpack",
  "nest ball",
  "net ball",
  "neutralization zone",
  "night maintenance",
  "night pokemon center",
  "night stretcher",
  "night teleporter",
  "nighttime mine",
  "no removal gym",
  "nugget",
  "ogre s mask",
  "old amber",
  "old amber aerodactyl",
  "old cemetery",
  "old pc",
  "old rod",
  "order pad",
  "ordinary rod",
  "paint roller",
  "pal pad",
  "panic mask",
  "paradise resort",
  "parallel city",
  "path to the peak",
  "peeking red card",
  "perilous jungle",
  "pewter city gym",
  "phoebe s stadium",
  "picnic basket",
  "plasma frigate",
  "plume fossil",
  "pluspower",
  "po town",
  "poke ball",
  "poke blower",
  "poke drawer",
  "poke healer",
  "poke pad",
  "poke radar",
  "poke vital a",
  "pokedex",
  "pokedex handy909",
  "pokedex handy910is",
  "pokegear 3 0",
  "pokemon catcher",
  "pokemon center",
  "pokemon circulator",
  "pokemon communication",
  "pokemon contest hall",
  "pokemon league headquarters",
  "pokemon park",
  "pokemon rescue",
  "pokemon research lab",
  "pokemon reversal",
  "pokemon tower",
  "pokenav",
  "pokestop",
  "postwick",
  "pot helmet",
  "potion",
  "power plant",
  "power tablet",
  "power tree",
  "practice studio",
  "precious trolley",
  "premier ball",
  "premium power pro",
  "prime catcher",
  "primordial altar",
  "prism tower",
  "professor s letter",
  "puzzle of time",
  "quad stone",
  "quick ball",
  "radio tower",
  "rainbow brush",
  "random receiver",
  "rapid strike scroll of the flying dragon",
  "rare candy",
  "rare fossil",
  "reboot pod",
  "recycle",
  "red card",
  "redeemable ticket",
  "repeat ball",
  "repel",
  "rescue carrier",
  "rescue stretcher",
  "research record",
  "reserved ticket",
  "reset stamp",
  "resistance gym",
  "return label",
  "reverse valley",
  "revitalizer",
  "revive",
  "ribbon badge",
  "risky ruins",
  "robo substitute team flare gear",
  "rocket s hideout",
  "rocket s minefield gym",
  "rocket s poke ball",
  "rocket s tricky gym",
  "roller skates",
  "root fossil",
  "root fossil lileep",
  "rose tower",
  "roto stick",
  "rotom bike",
  "rotom dex",
  "rotom dex poke finder mode",
  "rotom phone",
  "rough seas",
  "rubber gloves",
  "ruins of alph",
  "sacred ash",
  "saffron city gym",
  "sail fossil",
  "scoop up cyclone",
  "scoop up net",
  "scorched earth",
  "scramble switch",
  "sea of nothingness",
  "secret box",
  "shadow circle",
  "shopping center",
  "shrine of memories",
  "shrine of punishment",
  "sidney s stadium",
  "silent lab",
  "single strike scroll of the fanged dragon",
  "skaters park",
  "skull fossil",
  "sky field",
  "sky pillar",
  "sky seal stone",
  "skyarrow bridge",
  "slumbering forest",
  "snorlax doll",
  "snow leaf badge",
  "snowpoint temple",
  "space center",
  "special charge",
  "special red card",
  "speed stadium",
  "spicy seasoned curry",
  "spikemuth",
  "spikemuth gym",
  "spirit mask",
  "spongy gloves",
  "sprout tower",
  "stadium nav",
  "stark mountain",
  "startling megaphone",
  "steel shelter",
  "stormy mountains",
  "strange cave",
  "strange timepiece",
  "sunyshore city gym",
  "super potion",
  "super rod",
  "super scoop up",
  "supereffective glasses",
  "superior energy retrieval",
  "surfing beach",
  "surprise box",
  "suspicious food tin",
  "sweet honey",
  "switch",
  "switch cart",
  "switch raft",
  "switching cups",
  "tag call",
  "tag switch",
  "target whistle team flare gear",
  "team aqua ball",
  "team aqua hideout",
  "team aqua s great ball",
  "team aqua s secret base",
  "team galactic s invention g 103 power spray",
  "team galactic s invention g 105 poke turn",
  "team galactic s invention g 109 sp radar",
  "team magma ball",
  "team magma hideout",
  "team magma s great ball",
  "team magma s secret base",
  "team plasma ball",
  "team rocket s bother bot",
  "team rocket s factory",
  "team rocket s great ball",
  "team rocket s transceiver",
  "team rocket s venture bomb",
  "team rocket s watchtower",
  "team yell towel",
  "techno radar",
  "temple of sinnoh",
  "tera orb",
  "the rocket s training gym",
  "thunder mountain",
  "time space distortion",
  "timer ball",
  "tm machine",
  "tool box",
  "tool retriever",
  "tool scrapper",
  "tormenting spray",
  "tower of darkness",
  "tower of waters",
  "town map",
  "town store",
  "toy catcher",
  "trainers mail",
  "training center",
  "training court",
  "transformation tome",
  "treasure tracker",
  "trekking shoes",
  "trick shovel",
  "tropical beach",
  "tropical tidal wave",
  "tropical wind",
  "turbo patch",
  "turffield stadium",
  "twist mountain",
  "ultimate zone",
  "ultra ball",
  "ultra space",
  "underground lake",
  "undersea ruins",
  "unfair stamp",
  "unidentified fossil",
  "urn of vitality",
  "vermilion city gym",
  "victory cup",
  "virbank city gym",
  "viridian city gym",
  "viridian forest",
  "vs seeker",
  "wait and see hammer",
  "wait and see turbo",
  "warp point",
  "wela volcano park",
  "welcoming lantern",
  "windstorm",
  "windup arm",
  "wondrous labyrinth",
  "wondrous patch",
  "wyndon stadium",
  "xtransceiver",
  "yell horn",
]);
