// The legendary serpents that raid the play area: Gyarados and Rayquaza. Both
// are pixel copies of reference art (downsampled + octree-quantized), NOT hand-
// drawn. Gyarados is a straight trace of a side illustration (gyrados side.png).
// Rayquaza's only reference (ray_side.webp) is a model kit curled into an S, so
// it was UNROLLED into a straight serpent first (its body centerline traced as
// the skeleton's longest path, perpendicular cross-sections laid along a
// straight axis), then the clean head and an arm from the same photo were
// grafted on (scratchpad unroll.py / graft2.py). Each sprite natively faces
// right and mirrors with scaleX for leftward travel. To swim, it's sliced into
// thin vertical column-bands at render time (SnakeSprite) and each band runs an
// SMIL <animateTransform> phase-shifted down the body, so it SNAKES like a fish
// — head steady, amplitude growing toward the tail. The palettes are machine-
// derived from the photos, so their letters carry no fixed meaning.

const GY_IMAGE_HEX: Record<string, string> = {
  k: "#50ADDB", B: "#616564", L: "#FCFCFC", N: "#2B5266",
  W: "#A09F9B", c: "#E3D2AE", d: "#307093", R: "#508EAA",
  p: "#9D8F73", G: "#3987B0", E: "#C9B794", D: "#67C6F4",
  Y: "#1B394A", O: "#1E2C33", m: "#557789", a: "#847966",
};

// Gyarados: an exact pixel trace of the reference side illustration
// (gyrados side.png), mirrored so it natively faces right, downsampled +
// octree-quantized, background flood-filled away.
const GY_IMAGE = [
  ".........................................................................................................................................................................W.......................................",
  "........................................................................................................................................................................WLW......................................",
  "........................................................................................................................................................................WLWW.....................................",
  "........................................................................................................................................................................BLLB.....................................",
  "........................................................................................................................................................................WWLB....................BW...............",
  "........................................................................................................................................................................WBLWW...................BNR..............",
  ".........................................................................................................................................................................BLLB....W..............WNBW.............",
  "..........................................................................................................................................................W..............BLLB...WRB..............BdN.............",
  ".........................................................................................................................................................WWW.............BWLWW..BLB...............ORN............",
  "........................................................................................................................................................WWLB.........mW..BWLLB.WWWW...............aNNB...........",
  ".........................................................................................................................................................BLB.........BWB.WWLLW.BLLW................ORNW..........",
  ".........................................................................................................................................................BWLB........WBWWBLLLLBWLLB................WORO..........",
  "..........................................................................................................................................................BLB.........BWLBLLLLLLLLB.................BNNB.........",
  "..........................................................................................................................................................BLLB.........BLWLLLLLLLLB........BNBBW.....BRNW........",
  "..................................................................WB......................................................................................WWLBB...B....BLWLBBBBWWLR.......ENYNmNBOBBmBNRNW.......",
  "..................................................................WB.......................................................................................BLLRBWWmW...WBNdGRRRRRmNB.....WNGdYYRRNNmkGYNRNW......",
  "..............................................................BB..WBW.....................................................................................BWLLLLLLB...WNGkDDLLLLLLDkmmE..YkkkkNONRRNNddNRRmB.....",
  "...............................................................BB.WWB...................................................................................WBLLLLLLLLB..ENkDkkkDLLLLDDLDkGRNdNddNNNNONRRNNNRdRRB....",
  "...............................................................BWBBLm....................................................................................BmLLLLLLLW..NkkkkkkDDLDDDDDkkDNNNYGGRkkkdYONRRRRRdRB....",
  ".................................................WB............WBLWLWW....................................................................................BWWWWWLWB.WdkkkkkkkkkkkDDkkkkNNNNkkkkkkkRdYONRRRdRN....",
  "..................................................BB............BLLLLB.OB.................................................................................WNmmRRRdddYkkkkkkkkkkkkkRkkkkNdNOYNdGkkkkkGNBNNRRRBBB..",
  "...............................................B..BWW.........W.BWLLLB.BBW.......................................................................WWRWRRRWmNkDDDDkRkNdkkkkkkkkkkkkkNNdkDddGdNNYNNNdkRRdWLBOBRONdW.",
  ".............................................W.BBBLLB.........BBBLLLLW.mLB....................................................................WBmRkkkkLGGNRDkDkkRGdNkkkkkkkkkkkkkkkYYNdNdkkRddNOOGkkRNWLBLBNONGW.",
  ".......WBBOOOOOYNNdmBBWc....................WO.BLLLLB.........WWLLLLLLBLLB..................................................................WNdkDDDDDkkRRNkkkkkkRdNRkkkkkkkkkkkkkkkmBBYNNNdRGdYdkkkkdOOBOONNdkmBp",
  "...........OBWBBNNNNdRRmBRW..................YBBLLLLW..........BLLLLLLLLLR..........................................................WWRRmmdGNNDkkkkkDkGdNYkkkkkGddRkkRkkkkkkkkkkkkkRBLmNNNNNNNNNNNdkkNYNdGkkkBEc.",
  ".........WBWLLLLLWWmBBNRkkRmW...WBmRRW.WBRWW.BBmBBWWW..........BWLLLLLLLLW........................................................BNdRkkDkkkddDkkkkkdNBBBNkkkkkddkkkRRRRRRkkkkkkkkkkNLLLWBNNNNNYYNYdkkkkkkkDGaLB.",
  ".........WBWLLLLLLLLLLWBNRRRdNBNNRkkdNONGRkddNOdkkGNNBBBBBmWW...BWWLLLLLLW.......................................................BdkkkkDkdNdYGDkkkkkOccWpNkkkkGNdkkkGGRRRGRRkkkkkkkkBLLLLLWmBBNNNNdNkkkkkkkDNEcB.",
  "..........WBLLLLLWWmBmRRRLLDDmOGRkDRLpYkkkROBORkkkOBNONdkkkkGdRBBNNBmRWLLW................................................WWRRmmBNkkkkkGYBBBOGkkkkkDNBWWpNkkkkGNdkRRdddGGddGRRRRRRkdRLLLLLLLLLWNdNdYkkRkkkkGBcBB.",
  "..........WLLWBBBRRkLLLLLDkkkNNddLkkRNdGGkkNBNRkDkdNOdRkkDmBBmYNkkDkkkRmRWWWWWWW.......................................WBmkkDkddYNkkkkkNccWWNkkkkkkkkNOBBYkkkkRdNkRGdddddddddGGGGRdmLWWWWWWWLLLWYYYdkkdNkkkNWWWW.",
  ".........EBBNRkDLDDkkkRRkdkkkNNNNNNNGNBBBNNGNNddGLkGYGkkDDNpWBNkkkkkDmNNNOddRRRRmmW.........................WBBmmmmRmRBNkLLLRNBBOdkkkkkNpWWWYkkkkkkkkkdNNYkkkkGdYNkRGdddddddddddGRdWLWWWmBBBBBWWNkkkkkkNdkGBa....",
  ".......RBNGLkkRdddddddddNkDkkYpccccEWBcLccWaNaWpaBNNNGGLLkkdBYGkkkkkkOWWOGkkDDDDkkddBNNNmmmRWW...WWWWWW...BNdkDDDDkGdGYRkkLRBWWWBdkkkkkkNNNBYkkkkkDDkkGGdYkkkdNBBBNNddddddGGGdddGGGBLLLLLLLLLLWWmkkkkkRdYkdLW....",
  ".....WONdNNNNNNNNNNNBBONkDkdmBBpWWWWcBBcccccapLcLcEBBLBBBBNGNNLkDDDDDGBBNkkkkkkNBNNYYGkDDDkRdNNONdRRkkRmRBYkkkkkkRBBBBNkkkDdBWBWBNkkkkkkkGddYkkDkLddddddGNkkNacccLcpBBBBLOONddddGRkdNBBLLLLLLLLLmdkkkRRRNGBB.....",
  "......WWpBWWWWLLLLLLWBRDkdNW...WWWWWWWWBBapppOWccccWBcLLLcEpYNBNNNdGkkkYdkkkkkkOBWWOdRkkDkNBBBONkkkDkmBBNOdkkkkkkOpccBGDkkkkdNNNONkkkkDDkGGRNkkdNBppppppLOmNWLccccccccEEppLYYYNddRRkkkdBLLLLLWBmmNNdkkRRNNLW.....",
  "........WWLLLLLLLLLmNkkdNW.................W.WBBppEpLcccccccBpcccEpaBNGNdLkkkkDkdNNYdGkkDROWWpYRkkkDYBWWpOGkkkkkkkNBBOkkkkkkkkGdNYkkkLdNNNNdYdBWcLLLLLLccEOELcccccccEWWppppNNNYYdGRGGRkNLLLLNdGGdNNONkkkdBB......",
  ".......WBLLLLLLLWBNddNBW........................WWWWBBWEEWWEBpLcLLLLcEWYBBBBBNNdLkNNRkkkkDkNNONRkkkkkdNBBYGkkkkkkkkGdYkkkkDDDkkRRYGGBBpEcccEBaLLccccccccccBWcccccccccWWppppLNNNNYdddddGNLLLONkkdYNYNONkdBBW......",
  ".......OLLLLLWBNddNBW................................WBBBpppBpcccccccccBWLccccEpBdNNGGLkkkkkGNNkkkDDDDkGYNGkkkDDDDkkkNRDkkdNNNNNRNNWcLLLLcccpBccccccccccccWLcccccccccEWpppWaYNNNNNdddddOLLB.WNGNNNNddYdNEB.......",
  ".....WBWLWRBNdddNBW.....................................WWWWaLEcccccEEcpaLccccLLcEBBLBBBBBNNdNNkGGddddGkNNkkkLGGGGGkkNLGNBaWEEEppBLLcccccccEELccccccccccEEcaLcLcccccccEEWWpaONNNNNYYNNBBBBW...WBdNdddNNNEBaB.....",
  "...WNBmBOOYNNBBW.............................................WBBppEEEEEELcLcccccEcapLLLccccWBYNmBappppBNYNdNBBppppBBmYBWccLLLLccccBWLcccccEEcBpccccccccEEEWEBLcLLLLLccEpaaW.WONYOBW............WdNBNdNNdBpaB.....",
  "WBNYNNBBWW......................................................WBBBapapaBpEccEEEEpBcccccccccBLLLLLLLcccBBEccLLLLLccEBWLLccccccEEEpBLcccccEWWpLcccccccEEcEpppBBBppppapWW.....WBW................NmLWBNNkYpBLW....",
  "..........................................................................WBBappppELpLccccEEcapLcccccEEcBWLccccccccEcpaLcccccccEEWWLWcccEEWppELpcccccccEppBWW...................................BdW..BOkdBBLB....",
  ".............................................................................WWWWppWBpEccEEEEWLccccccEEcpBccccccccEWWpLcccccccEEEEppLEccccEpppa.BBaaapBaW.......................................WNW...BdkNBBa....",
  ".....................................................................................WBBBBBBapBBBBaaaapppBBppWEEEpppppBBEEccccEEppapBBaaaaaBaW..................................................cNB....BmNpBOB...",
  "...........................................................................................................WWBBBBaaapW.WBBBBBBBBpWW..............................................................NN.......pEBB...",
  ".................................................................................................................................................................................................BN........ppB...",
  ".................................................................................................................................................................................................BN........WBW...",
  ".................................................................................................................................................................................................BdW.............",
  ".................................................................................................................................................................................................Bdc.............",
  ".................................................................................................................................................................................................mmE.............",
  ".............................................................................................................................................................................................R...BB..............",
  "............................................................................................................................................................................................WN..WmB..............",
  ".............................................................................................................................................................................................dRmdNE..............",
  ".............................................................................................................................................................................................WNBBW...............",
];

const RAY_IMAGE_HEX: Record<string, string> = {
  k: "#1FA95D", B: "#54B26F", L: "#EE6552", N: "#000000",
  W: "#EDD10F", c: "#67B98A", d: "#72C48C", R: "#93D1A5",
  p: "#9FB229", G: "#989E58", E: "#E85738", D: "#13893B",
  Y: "#EBDC52", O: "#ED9B98", m: "#F3F5F3", a: "#136327",
};

// Rayquaza: model kit (ray_side.webp) body UNROLLED straight; the head (down-
// neck masked, rotated ~32° to point forward) grafted ON the tube axis — the
// neck join sits on the tube's centerline so the body flows into the head —
// plus the clawed arm hanging from the underside just behind the head.
const RAY_IMAGE = [
  "............................................................................................................................................................................................................................................................................................................................................................................................................................................",
  ".....................................................................................................................LELONLLO........................................................................................................................................................................................................RdddRRR................................................................................................",
  "....................................................................................................................LNGLLELLELO...........................................................................................................................................................LLLL.........LNLLLLL.....................RBNBBkBBNdRRRN...........................................................................................",
  ".................................................................................................................LLLEkkBNBkkBELLLO.......................................................................LELONLLLLLLLLLL.................................................................LLLLLLLLLLLLLLLLLEEELL...................dNBBkkkkkkkkBNddRRRR......................................................................................",
  "..........................................................................................................LEEO...GBNBkkkkkkkkkNELL......................................................................LLGLLLLLEEEEEEEE................................................................LLENNEEEEEEEEEEEEENkNEEL..................dkkkkkkkkkkkkkkkBBddddRRN.................................................................................",
  "..........................................................................................................LLLLNmNBkkkkkkkkkkkkkkNL...................................................................LLLLNkkNNNNkkkkkkkG................................................................LNkkkkkBBBBBBBBkkkkkkkNLO..................BkkkkkkkkkkkkkkkkkkBBBdddRR.......................................RRR....................................",
  ".........................................................................................................OLBNELNLBkkkkkkkkkkkkkkkL...................................................................LELLBkkkkkkkkkkkkkB...............................................................LGkkkkkkkkkkkkkkkkkkkkkkNO...................dkkkkkkkkkkkkkkkkkkkkkBBNddRRR.................................RdBBddRRRRN..............................",
  ".........................................................................................................OEkBEEEEkkkkkkkkkkkkkkkkL...................................................................LNEEkkkkkkkkkkkkkkBL.............................................................LNkkkkkkkkkkkkkkkkkkkkkkkGL....................RkkkkkkkkkkkkkkkkkkkkkkkkBBBddRR.............................dBkkBBBBBBddRRRR..........................",
  "........................................................................................................OLEkkLLLNkkkkkkkkkkkkkkkkL..................................................................LLkNNkkkkkkkkkkkkkkBL.............................................................NLkkkkkkkkkkkkkkkkkkkkkkkGL......................BkkkkkkkkkkkkkkkkkkkkkkkkkkBBNddRR....................ddRNdBkBkkkBBBBBBcddRRR........................",
  "........................................................................................................OENkkBNLBkkkkkkkkkkkkkkkkLO.................................................................LNkkkkkkkkkkkkkkkkkBL.............................................................LEkkkkkkkkkkkkkkkkkkkkkkkBL.......................dkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBdddRR.............dddNYYBkkkkkkkkBBBBBBBddddRRRN....................",
  "........................................................................................................LEBkkkkkkkkkkkkkkkkkkkkkkNO................................................................LLBkkkkkkkkkkkkkkkkkkL.............................................................LLkkkkkkkkkkkkkkkkkkkkkkkBL........................dNkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBNddRR........dcNNWYNBkBBkkkkkkkkkBBBBBBcBdddRRRR.................",
  "........................................................................................................LEBkkkkkkkkkkkkkkkkkkkkkkNN..........................................................ENLmmmLEkkkkkkkkkkkkkkkkkkkL.............................................................LLkkkkkkkkkkkkkkkkkkkkkkkBN.........................RBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBddRR...RcNWWWGBkkkkkkkkkkkkkkkkBBBBBBBBBcdddRRR..............",
  "...................................................................................................RdcRNNNBkBBBBkkkkkkBkkkkkkkkkkGL........................................................RNGGGNRNNNkkkkkkkkkkkkkkkkkkkNO............................................................LEkkkkkkkkkkkkkkkkkkkkkkkBL...........................dkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBddddNWWNBkkBkkkkkkkkkkkkkkkkkkkkkBBBBBBBcddddRR...........",
  "...................................................................................................RdddcddccdccdBBkkkBBBBBBBBkkkkBL.......................................................cdBNNNBBBNBBBBBkkkkkkkkkkkkkkkNLm..........................................................mLEkkkkkkkkkkkkkkkkkkkkkkkBLO...........................RBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBcNNBkkkkkkkkkkkkkNaaaaaaaaNNNkkkkkkBBBBBccddRdRR.......",
  "..................................................................................................RRdddddccdddddcBBBBBBBBBBBBBBkkBLRc.....................................................cdcBBBBBBBBBBBBBBkkkkkkkkBBkkkBNcdBcd.....................................................RONNkkkkkkkkkkkkkkkkkkkkkkkkNGBc..........................NBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBkkBkkkkkkkkNNNNNNNNNNNNNNNNNNNkkkBBBBBBccddRRRN...",
  "..................................................................................................RRRRRRRRRRRRddddBBBBBBBBBBBBBBBBBBNd.....NRRRR..Rccccdd.................................BdBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBN..................................................RckkNakkkkkkkkkkkkkkkkkkkkkkkkBkkkR...........................dkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBkkNNNNNNNNNpNNNNNNkBBBBBccddcdddR..",
  "...........................................................................................RRRRRRBRRRRRRRRRRdddddddccBBBdddcBBBBBBBBBBR.dBBNNNkNNBNBNNBBBBBBddBBBBBBcddddcddddBcddRdcccBd.NdBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkR.....RRdRcdcccccBBBddddccddcccccccccBBccccdcR.....ckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkR...cBBBcBcBBBBBdcccBcccBBcBcdkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBNNNNNNNNppNaBdBBBBBBBccdcdcdNd..",
  "............................................................................NNRRRRRRRRRRRRRRRRRRdacRdddddddddddddddccBBBcccBBBBBBBBBBkBRkkkBBBBBBBBBBBBBBBBkkkkBBBBBBBBBBBBBBBBBBBBcdcdddcNBccddcccBBBBBBBBBBBBBBBBBBBBBBBBBBBkBmckdddddNNNNNNNdNNdBBBNBBBBBBBBBBBBBBBBkkkkkkkBkBmckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkcmckkkkkkkkBBBBBBBBBBBcBBBBBBBdBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBNNNNNNNpNNBcBBBcBNNBBBdNddcddR.",
  ".............................................................RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBNcdddddddddccdddddccBBBBBBBBBBBBBBBBaNaBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBccccccBNBNBddddddddddBBBBBBBBBBBBBBBBBBBBBBBBBkNNkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkkkkkkkkckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkaNkkkkkBBBBBBBBBccccccccccBBBBBdNkkkkkkkBkkkBdcddBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBNNNNNNBcdBBBBBBBGGNNRdccddcd.",
  ".....................................RRRRRRkkBRdccRRRRRRddRRRRRdRRRddRdRRRRRRRRRRRRRRRRRRRRRRRRRkNNdddddccdcccccdddccBBBBBBBBBBBBBBBBaNaNBBBBBBBBBBBkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBccccBdkakRRRRRRdddddddccBBBBBBBBBBBBBBBBBBBBkNakBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkkkaNkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkNNkkkBBBBkBBBNNNGGdccddddcddccccddkBNYYRkBccBBkkBkNBcBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBBBBcNNBBBBBGLLLLLmmm..NNdcR.",
  ".............................RdNRddRdddcccdaNNddddddddBBBBBBBcddcdddddddddddRddcNGGGNNNNNRRRRRRRkNcdcccccBBBBBBcccccBBBBBBBBBBBBBBBBBaNaNBBBBBkBBGNNNNpGBBBBBBBBBBBBBBBBBcccccccccddccccdkNkddRRRRddddddddccccccccccccccccccBcBkNakBBBBBcBNNNNNNNBcccccccccBcccBBNNNNNNBBBBBBBkkaNkkkkkkkkkkkkkkBkBBBBkkkkkkkkkkkkBkNNkBBBBBBNWWWWWYYYYNGcddddddddcNYYYYYWWYYYYNBBBBBkaNkRBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBBkkkBBGGLLLLLLN...mmmmm.....",
  "......................RRRddRdddddddBcccBBdBNNBcBcBcBNNYYYWYYYGGBcccddddddddddBNYYYYYYYYYYYGdRRRRNNcdcBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBNaNaBBBBBBNWWWWWWWWWWNBBBBBBBBBBBBBccBBNNNNNNNGNdddddkNNdRdddddccdddddddddddcccccccccccccBckaakccccBNYYYYYYYYYNNddddddccdcNYYWWWWWWWWNBBBBBkNNkkkkkkkkkkBBBBBBBBBBBBBBBBBkkkkkBBNNkBBBBNWWWWWWWWWYYYYNBdcddddcYYYYYYNNNYYWYYYNBBBBaBRBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBGNLLLLLLLO.......mmmm.....",
  "...............RccRcddddccccBBBBBBBBBBBBBdkNkBBBBBNYWWWWWWWWYWYYBccdddcdcdddGYYYYYYYYYYYYYYNcdddNNBBBBBBBBkkkkkBBBBBBBBBBBBBBBBBBBBBNaNNBBBBGWWWWWNNNWWWWWWNBBBBBBBBBBcBNWYYYYYYYYYYNcdddBBNBcBBBBBBBcccddddcdddccccccccccccccBkNNBccBNYYYYYYYYYYYYYNddddcddcNWYYYWWWWWWWWWBBBBBaNBkkkkkkkkBBBBBBBBBBBBBBBBBBkkkkkBBNNkBBGWWWWWGBBBBBBGWWWNBccBcBNYYYGBBBBBcBBGWWYYBBkNNBkkkkkkkkkkkkkBkkkkkkkkkkkkkkkkkkkkkBBGNLLLLLLLLLL..........mmm.....",
  "......RRdNLONNdddBBBBBBBBBBBBBBBBBBBBBBBBBkNNkBBBGWWWpGGGBBGGWWWWBcNBcBNcBBBYWWpGBBBBBBGpWWYpBcBaNBBNLLLLLNNGGBBkkBBBkkBBkkkkBBBBBBBBkNNkBkpWWWpBBkkkBBBpWWWWBBBBBBBBBpWWWWWWWYYYYYYYYBddkBNkkBLLNGGBBBBBBccccBBBBBBBBBBBBBkkBkkNNBdBNYYWWGGBBBGNWWYYNcddcNBNWWWNGBBBBGpWWWWBBBBNNBkkkkkkkkBBkkkBBBBBBkkkkkkkkkkBkBBNNBBBWWWpBBBBBBBBBBBpWWpBBBBGWWpBBBBBBBBBkBBpWWGkBNBkkkkkkkkkkkkkBBkkkkkkkkkkkkkkkkkkBGNLLLLLLLLOOLLLO...........m......",
  ".dBcdddkBLELLLLNNGBGBBBBBBBBBBBBGGGGGNNBkkkNNppGpWWpBkkkkBkkkBGWWWBkBkkkkkBWWWBBBBBBBkkBBBpWWNkkaNNBLLLLLLLLLLLLGBkkkBGLLNGBBkkkkBBBNkNNkkBWWNBkkkkkkBkkkBpWWWBBBBBBBWWWWWNBBBBBBBGNWWWBBkNNkkkLLLLLLLGGBkkBBBBBkkkkkkkkkBBBGBkkNNBBBWWWGBcccBBccBGWWWGBBBBGWWWBBBBBBBBBBpWWWBBBNNBkkkkBkkkkkkkkkkkkkkkkkkkkkkkkkkBBNNkkGWWpBkBBBBBBBBBBBWWWBkkBWWNkkkkkkkkkkkkkkpWWBRBkkkkkkkkkkkkkBBBkkkkkkkkkkkkkkBGLLLLLLLLLLLLN...LO...................",
  "ckkkkkkkGLLLLLLLLLLLLLLLLLNLLLLLLLLLLLLNkkkNNWWWWWNkkkkkkkkkkkkNWWNpppppppNWWBkkkkkkkkkkkkkpWpBkaNakLLLLLLLLLLLLLLNGNLLLLLLLLNGBBBBkBBNNaNWWWBkkkkkkkkkkkkkBWWNBBBBBNWWpBBkBkkBBBkkBGWWpBkaNakkEELLLLLLLLGBBBBkBBBGGGGGGGLLLENkkNakBWWWBBBBBBBBBBBBBWWNBBBBWWWBBBBBBBBBBkkpWWNkBNNBkBkkkkkkkGGGGGGGGGGGLLLLGBkkBBBBBNNkkWWpkkkkkkkkkkkkkkpWWWNNWWWNkkkkkkkkkkkkkkkNWNBkkkkNNNNNNBkBBBBkkkkkkkkkkkBGNLLLLLLLO....LLLO........................",
  "ckkkkkkkLELLLLLLLLLLLLLLLLLLLLLLLLLLLLLNkkkNNppNWWNkkkkkkkkkkkkNWWWWWWWWWWWWpkkkkkkkkkkkkkkNWWWNpNNkNLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLkkBNNNWWWWkkkkkkkkkkkkkkkpWWWWWWWWWGkkkkkkkkkkkkBkGWWNNNNNBkEELLLLLLLLLLLLLLLLLLLLLLLLEEEENkkNakBWWBkkkkkkkkkkkkkpWWGBBpWWBkkkkkkkkkkkkkpWWkkNNkBLLBkBBNLLLLLLLLLLLLLLLLLLLLLLLkBNNDpWWBkkkkkkkkkkkkkkpWWWWWWWWpkkkkkkkkkkkkkkkpYBkkkBWWWWWWWNkBBBBkkkkkkkkBNLLELLLLN.........OO.........................",
  "RdkkkkkBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLNkkkaNkkkNWWpkkkkkkkkkkDNWWNNNNpppppWWNkkkkkkkkkkkkkpWNNNNNNkNLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLNkNaNNNpWWNkkkkkkkkkkkkkkNWWWWWWWWNkkkkkkkkkkkkkkkBWWWWpNNBkEELLLLLLLLLLLLELLLLELLLEEELLLENkkNpWWWWkkkkkkkkkkkkkkBWWWWWWWWBkkkkkkkkkkkkkBWWpNNNkNLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLkBNNNWWWBkkkkkkkkkkkkkBWWWppppNWWNkkkkkkkkkkkkkkYBkkkBppppppppGBBBBkkkkkkGLLLLLLLLO.......................................",
  "..ddccBkkBGGLLLLLLLLLLLLLLLLLLLLLLLLLLLNkkkaNkkkkpWWNpNkkkkkBpNWWNkkkkkkkkkpWWDkkkkkkkkkkkNWWNkkaNNaBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLEaNaNNkkpWWkkkkkkkkkkkkkkpWWpBBpWWpkkkkkkkkkkkkkkkNWWWNNNNNNBLLLLLLLLLLLLLLLLLLLLLLLLLLLLLNkaNpWWWpkkkkkkkkkkkkkkpWWWWWWWWpkkkkkkkkkkkkkkWWWWNNkNLLLLLLLLLLLLLLLLLLLLLLLLBNLLLEkBNNpWWWpkkkkkkkkkkkkBWWWBkkkkBNWWpBkkkkkkkkkkkNYkkkkakkkkkkkkkBBBkkkkkkBLLLLENNO.........................................",
  ".......dcdNNBBGGGNLLLLLLLLLLLLLLLLNNGGGkkkkkNkkkkkpWWWWNNppNWWWWNkkkkkkkkkkkNWWpNkkkkkkkDpWWpkkkkNNNkkDBBNNNNLLLLLLLLLLLLLLLLLLLLLLLNkkNNakkNWNpkkkkkkkkkkkpWWNkkkkpWWNkkkkkkkkkkkkkNWWWBkkaNaBkkBNLLLLLLLLLLLLLLLLLLLLLLELLENkNNNBpWWBkkkkkkkkkkkBpWWpBBBBpWWpkkkkkkkkkkkkNWWppNakNLLLLLLLLLLLLLLLLLLLLLLLBkcNLLLkNaNkkBWWNBkkkkkkkBBpWWWBkBkBBkBNWWWNBBBkkkBBpWYpkkkkkkkkkkkkkkBkkkkkkkkkBENNNNNNNNO......................................",
  "...........RccdkNBBBBBBBBBBBBBBBBkBkkkkkkkkkNkkkkkkkNpWWWWWWWWpBkkkkkkkkkkkkkpWWWNppppppNWWpkkkkkNNNakkkkkkkkkNNELLLLLLNNNLLLLLLLLLLNkkNNakkkpWWpNNkkkkkNNNWWNBkkkkNWWWNkkkkkkkkkkkpWWWGkkkaNNBkkkkBBGNLLLLLLLLLLELLLLLLLLLLLBkNakkkWWWpBkkkkkkkBpWWWpkkkkkkpWWWNBkkkkkkkkpWWNkkNNkaLLLLLLLLLLLLLLLLLLLLLLGBBkBNLLkkNNkkkBWWWWpppppNWWWWWBkBBBBBBBBGWWWWWWWWWWWWYWBkBBkkBkkkkkkkkkkkkkkkkkkkNNELLLLENLLL....................................",
  ".................dBBckBBkkkkkkkkkkkkkkkkkkkkakkkkkkkkkkBNNNNBkkkkkkkkkkkkkkkkkNpNWWWWWWWNpNkkkkkkaNNakkkkkkkkkkkkNNNNNkkkkkBNNLLLNNNBkkaNNkkkkpNWWWNNpNNWWWWpkkkkkkkNWWWppBkkkkkBNWWWWGkkkkkNNBBkkkkkkkBGLLLLLLLLLNGGGGGGGBBkkkNNkBBBpWWWNpGGppWWWWWGkkkkkkkkpWWWWNNppNpNWWWpkkkNNkDLLLLLLLLLNNNNNNNNNNBkBBBBBkBNBkBaNkkkkBpWWWWWWWWWWWNBkBBBBBBBBBBBGpWWWWWWWWYBBBBBBkkBBBBBBBBBBBkkkkkkkkkBNELLLNONLLLLLO.................................",
  "........................dcccBdBcBkkkkkkkkkkkkcNkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkNNppppNkkkkkkkkkkNNNkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkNNakkkkkpNpNNWNNNppBkkkkkkkkkBpWWWWWNpNNWWWWNBkkkkkkaNNBkkBBBkkkkBBBBBBBBBkkkkkkkkkkkBkNNkBBBBGWWWWWWWWWWNGBkkkkkkkkkkBpWWWWWWWWWWpNkkkkNakkBLLLLLLNBkkkkkkkkkkkkkBBBBBkkkkkaNDkkkkkBpppNWNpGBBBBBBBBBBBBBBBBBBBBGGGGBBBBBBBBBkkBBBBBBBBBkBkkkkkkBBBBkkNNLLLNONLLLLLLOO.............................",
  "................................ddccBBckkkBBB..ccccccBkkBkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkNaNkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkNNakkkkkkkkkkNNkkkkkkkkkkkkkkkkBppWWWWWWWWpkkkkkkkkkaNNBBBBBBBBBBkkkkkkBBBBBBBBBBBBBBBkNaBBBBBBBBGGGpGGBBBkBBkkkkkkkkkkkkBBNppppNBkkkkkkaakkkkBBBBkkkkkkkkkkkkkkkkkBBBBBkBckNNakkkkkkkkkkkkkkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkBBBBBBBBBkBBBBBBBBBBBkkkkkNLLLNOONNNOOLO..O.........................",
  "..............................................................ccckkkcBkkcBkkkkkkkkkkkkkkkkkkkkkkkkkkakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkaNakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBBBBBBBkkkkkkkkkkkkNNkkkkkBBBBBBBBBBBBBBBBBBBBBBBBBBkNNkBBBBBBBBBBkkkBBBBkBkkkkkkkkkkkkkkkkkkkkkkkkkkkaNkkkkkkkkkkkkkkkkkkkkkkkkkkBBBBBkBRkNakkkkkkkkkkkkkkkkBkkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkBBBBBBBBBBkkkkkkkBNLLLOOOOOLNNLOO........................",
  ".................................................................................BccBcBkcckkkkkkkkkkkckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkNNRkkkkkkkBBkkkBBBkkkkkkkkkkkkkkkkkkkkkkkBBkkkkkkkkBR.BkkkkkkkBBBBBBBBBBBBBBBBBBBBBBBBNkBBBBBBBBBNNNNNNNNBBBBBBBBBkkkkkkkkkkkkkkkkkkkkkaNkkkkkkkkkkkkkkkkkkkkkBkkkkkBBBBBkkBNNkkkkkkkkkkkkkkBkBBBNBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkkkBBBBBBBBcBkkkkkkkkkBNLLLOOOLLOOO........................",
  "......................................................................................................kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkN...................cNcccBccBcBccccccBcccccccccBBcN..BkkkkkkkkkkkBBkkkkBkkkBBBBBBBBBB.ccBBBccccdcBBBccBcBccdccBBcRcccBBBBBcBBBBkkkkkkkkmdkkkkkkkkkkkkkkkkkkkkkBkkkkkBBBBBBkRRBccccccBBBcckBBkcccccccdddcdccdBBBBBBBBBBBccBccccccccccccBkkkBBBBBBBBdBkkkkkkkkkkkkNLLOOOOOOLO.......................",
  "......................................................................................................ccNNkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkBc....................................................BakkkkkkkkkkkkkkkkkkkkkkkkkkkBBc..............................................NcN..dkkkkkkkkkkkkkkkkkkkkkkBkkkkkBBBBBkBBcBBBdR....................................................kkkBBBBBBBBdkB.NBkkkkkkkkkkBLLOOOOOOON.....................",
  "........................................................................................................LNkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkB......................................................NDDkkkkkkkkkkkkkkkkkkkkkkkkkkdR....................................................kkkkkkkkkkkkkkkkkkkkkkBBkkkkBBBBBdcccBBBBBBcdd................................................kkkBBBBBBBBNkc....cBkkkkkkkkkBNLLNOOOOO....................",
  "........................................................................................................NEkkkkkkkkkkkkkkkkkkDkkkkDDkkDaNGN......................................................NDDDDDDkkkkkkkkkkkkkkkkkkkkDNN.....................................................BkBBkkkkkkkkkkkkkkkkkkkkkkkkBBBBdBBBBBBBBBBBBNdR..............................................kkBBBBBBBBdBk........ckkkkkkkkkkNLLLOOOOO..................",
  "........................................................................................................LEkkkkkkkkkkkkkkkkkkDaaaaDkkkkNNO.......................................................NkDDDDDDkkDkDkDDDDDDDDDDDDDNN........................................................OEBNNNNkkkkkkkkkkkkkkkGkkkkkkBBBBBBBBBBkkBBBBBdd............................................kkBBBBBBBBdkB..........dkkkkkkkkkkNLLLLLNNO................",
  "........................................................................................................LEBkkkkkkkkkkkkkkkkkNNNNNkkkkkNNL.......................................................NkkDDDDDDDDDDDDDDDDDDDDDDDDNN.........................................................LNLLENBkkkkkkkkkkkkkkEGkkkkBcBBBBBcBBkkkBBBBBBBR...........................................kkBBBBBBBBdkc.............kkkkkkkkkkNNLLLLN................",
  "........................................................................................................LEBkkkkkkkkkkkkkkkkNNNENNBkkkkNNL.......................................................NkkkDDDDDDDDDDDDDDDDDDDDDDDNN.........................................................NNLmOLNkkkkkkkkkkkkkkELckkBccBBBBdcBBkkkkBBBBcBN...........................................kkBBBBBBBdBk...............RckkkkkkkkkkkNO.................",
  "........................................................................................................OLBkkkkkkkkkkkkkkkkNNEENENkkkkkNL.......................................................NkDkDDDDDDDDDDDDDDDDDDkDDDkNN..............................................................LLkkkkkkkkkkkkkBN..NBBcBBBBBdBkkkkkkkBBBdRdd..........................................kkBBBBBBBdkB.................Rckkkkkkkkkd..................",
  ".........................................................................................................LGkkkkkkkkkkkkkkkkEELLENNkkkkkEL.......................................................NkkkkkkDDDDDDDDDkDDDDkkkDkkNN...............................................................LkkkkkkkkkkkkkB...RkBBcBBBBBBkkkkkkkkBdmmmN..........................................kkNBBBBBBdkB...................dkkkkkkk....................",
  ".........................................................................................................LLkkkkkkkkkkkkkkkBELONLENkkkkkNL.......................................................NkkkkkkkDDDDkDDDDkkkkkkkkkkNN...............................................................LBkkkkkkkkkkkkB...dkkBBBBBBBBkkkkkkkBRm...m..........................................kNBBBBBBdBk......................ckkkc.....................",
  ".........................................................................................................LEENkkkkkkkkkkkkkNLO.OLENkkkkkNE.......................................................ENkkkkkkkkkkkkkDkkkkkkkkkkkNE...............................................................LBkkkkkkkkkkkkN...RkkkBBBBBBkkkkkBRcmmmm..m...........................................dBBBBBBdkk........................cR......................",
  ".........................................................................................................LLLENkkkkkkkkkNENEL...OEEkkkkkNE.......................................................LENNNakkkkkkkkkkkkkkkkNDkkDNL................................................................BkkkkkkkkkkkkG....kkkkkBBBBkkkkBBBmmmmm..............................................dBBBBBcBkB................................................",
  "............................................................................................................LLENkkNNNBNLLNL....OLENkkkkNE........................................................LLENNNNkkkkkkNDkNNNNNNNNNNNE................................................................GBBBBBBBBBBGGL....ckkkkBBBBBkkNmRNdmmmm..............................................dBBBBBdBk.................................................",
  "..............................................................................................................LENEELLLLL........LENNNNNEL..........................................................NLLLNNNNNNNNNNNNNELEEEELLL................................................................LLLLLLLLLLLLLL....RkkkkkkBBBBcNRmdcNmmmm............................................RNBBBBBdkk.................................................",
  "...............................................................................................................LEEL.............NLLLEELLO..............................................................LENNLLLLEEOOOOOOOLLOO.................................................................LNNNNNNNNONON......ckkkkkkBBBRNRmRR.mmm..............................................NBBBBcckB.................................................",
  "...................................................................................................................................OLL..................................................................LEL......................................................................................................cckkkkkBcmmNmmmm.mm..............................................NBBBNdBk..................................................",
  "...................................................................................................................................................................................................................................................................................................................dkkkkBRmmNmmmm.................................................NBBBBBB...................................................",
  "....................................................................................................................................................................................................................................................................................................................NBkkRmmmmmmmm.................................................dkkkkd....................................................",
  "......................................................................................................................................................................................................................................................................................................................Rmmmmmmmmmm.................................................dkkBR.....................................................",
  "........................................................................................................................................................................................................................................................................................................................mmmmmmmm..................................................dR........................................................",
  ".........................................................................................................................................................................................................................................................................................................................mmmmmm.............................................................................................................",
  "............................................................................................................................................................................................................................................................................................................................................................................................................................................",
];









export type SerpentSprite = {
  name: string;
  palette: Record<string, string>;
  // "cross": swims straight across at a fixed height, alternating direction.
  // "prowl": slithers in from a side edge, dives, then wanders the open water.
  behavior: "cross" | "prowl";
  // An exact traced sprite (tail-to-head, natively facing right). At render time
  // it's sliced into thin vertical columns and a traveling sine runs down them,
  // so the whole body SNAKES like a swimming fish (head steady, tail sweeping).
  image: string[];
  // On-screen size: each design pixel renders at renderScale * PX screen px. The
  // unrolled Rayquaza is very long, so it renders smaller than Gyarados to fit.
  renderScale: number;
  // Peak wave amplitude at the tail, in DESIGN px (the head barely moves). Tune
  // per serpent to its girth so the snake reads without tearing the silhouette.
  waveAmp: number;
};

export const SERPENTS: SerpentSprite[] = [
  {
    name: "gyarados",
    palette: GY_IMAGE_HEX,
    behavior: "cross",
    image: GY_IMAGE,
    renderScale: 1.2,
    waveAmp: 9,
  },
  {
    name: "rayquaza",
    palette: RAY_IMAGE_HEX,
    behavior: "prowl",
    image: RAY_IMAGE,
    renderScale: 0.8,
    waveAmp: 11,
  },
];
