// The legendary serpents that raid the play area: Gyarados and Rayquaza,
// both drawn in SIDE PROFILE (dorsal fins up, belly down) as strips of 24-row
// pieces laid tail->head along +x. Travel direction is a plain horizontal flip
// (side views have a real up, so no rotation). Both enter side-on from a screen
// edge — Gyarados cruises straight across, Rayquaza slithers in and prowls the
// open water. Slices are deliberately NARROW (8-12 cells): the per-piece
// wave phase lag stays small between neighbors, so joints can't visibly
// disconnect. Pieces overlap by 3 cells with the head-ward neighbor painting
// on top, so every piece keeps its rightmost 3 columns plain tube.
//
// The heads are generated by a painter script (shapes + auto-outline, like the
// original Clefairy silhouette) and checked against PNG renders; the grids
// below are its frozen output.
//
// NOTE: only GYARADOS is hand-authored segmented pieces (below); RAYQUAZA is an
// EXACT pixel trace of the reference model kit (ray_side.webp: trimmed,
// downsampled, octree-quantized, background flood-filled away). It's a single
// sprite kept whole and wagged as one body (see the .serpent-wag class), since
// the model's S-pose can't be cut into a snaking tube.
//
// Gyarados legend: k outline | B body blue | L highlight | N crest navy |
// W fin/fang white | c belly cream | d cream shade | R maw dark red.
// (Rayquaza's palette is machine-derived from the photo — its letters carry no
// fixed meaning, they're just the traced colors.)

const GY_HEX: Record<string, string> = {
  k: "#101820", B: "#4098D0", L: "#78C8E8", N: "#1B4E74",
  W: "#F8F8F8", c: "#F0DCA8", d: "#C89860", R: "#8E1C1C",
};
// Gyarados body segment: a rounded blue back over a cream belly, with a navy
// seam on the tail-ward edge dividing it from its neighbor. No dorsal fin — in
// the reference the big three-pronged crests sit only at intervals, so those
// ride the GS_FIN segments and most of the body is smooth tube.
const GS_BODY = [
  "..........",
  "..........",
  "..........",
  "..........",
  "..........",
  "kkkkkkkkkk",
  "NLLLLLLLLL",
  "NBBBBBBBBB",
  "NBBBBBBBBB",
  "NBBBBBBBBB",
  "NBBBBBBBBB",
  "NBBBBBBBBB",
  "NBBBBBBBBB",
  "NNNNNNNNNN",
  "Nccccccccc",
  "Nccccccccc",
  "Nddddddddd",
  "Nddddddddd",
  "kkkkkkkkkk",
  "..........",
  "..........",
  "..........",
  "..........",
  "..........",
];

// Gyarados finned segment: a three-pronged white dorsal fin rising off the
// back, like the crests spaced down the reference serpent's spine. The fin sits
// in rows the neighbor segments leave empty, so the 3-col overlap never clips it.
const GS_FIN = [
  ".....kk.....",
  "....kWWk....",
  "..k.kWWk.k..",
  ".kWkkWWkkWk.",
  ".kWWWWWWWWk.",
  "kkkkkkkkkkkk",
  "NLLLLLLLLLLL",
  "NBBBBBBBBBBB",
  "NBBBBBBBBBBB",
  "NBBBBBBBBBBB",
  "NBBBBBBBBBBB",
  "NBBBBBBBBBBB",
  "NBBBBBBBBBBB",
  "NNNNNNNNNNNN",
  "Nccccccccccc",
  "Nccccccccccc",
  "Nddddddddddd",
  "Nddddddddddd",
  "kkkkkkkkkkkk",
  "............",
  "............",
  "............",
  "............",
  "............",
];

// Gyarados tail: the big white ragged fan at the tip, blue tail tapering in.
const GS_FAN = [
  "....................",
  "..kk................",
  ".kWWkk..............",
  "kWWWWWk.............",
  ".kWWWWWk............",
  "kWWWWWWWk.....kkkkkk",
  ".kWWWWWWWkk...LLLLLL",
  "kWWWWWWWWWWk..BBBBBB",
  ".kWWWWWWWWWWkkBBBBBB",
  "kWWWWWWWWWWWkBBBBBBB",
  ".kWWWWWWWWWWBBBBBBBB",
  "kWWWWWWWWWWWkBBBBBBB",
  ".kWWWWWWWWWWkkBBBBBB",
  "kWWWWWWWWWWk..BBBBBB",
  ".kWWWWWWWWk...cccccc",
  "kWWWWWWWWk....cccccc",
  ".kWWWWWWk.....cccccc",
  "kWWWWWk.......dddddd",
  ".kWWkk........kkkkkk",
  "..kk................",
  "....................",
  "....................",
  "....................",
  "....................",
];

// Gyarados head: navy three-prong crest, white eye under a navy brow, gaping
// fanged maw with the cream jaw rims, navy cheek fin, white chin barbel.
const GS_HEAD = [
  "......kNk..kNk......................",
  "......kNNk.kNNk.kk..................",
  "......kNNk.kNNk.kNk.................",
  ".....kNNNNkNNNNkNNNkkk..............",
  ".....kkkNNNNNNNNNNNNNNkkkkk.........",
  "kkkkkk..kBBBBBBBBBBNWWWBBBBkkkk.k...",
  "LLLLLL.kBBBBBBBBBBBWWkWBBBBBBBBkBkk.",
  "BBBBBBkBBBBBBBBBBBBWWkWBBBBBBBBBBBBk",
  "BBBBBBkBBBBBBBBBBBBBBBccccccccccccck",
  "BBBBBBkBBkkkkBBBBBBBBBBWWWRRRWWWRRk.",
  "BBBBBB.kkNNNNBBBBBBBBBBRWWRRRRWWRRk.",
  "BBBBBB.kNNNNNBBBBBBBBBRRWRRRRRWRRRk.",
  "BBBBBBkNNNNNNBBBBBBBBBRRRRRWRRRRRWk.",
  "BBBBBB.kNNNNNBBBBBBBBBBRRRRWWRRRRWk.",
  "cccccckckNNNNBBBBBBBBBBBRRWWWRRRWWk.",
  "ccccccccckkkkcccccccccccccccccccccck",
  "ccccccccccccccccccccccccccccccckkkk.",
  "ddddddkkdcccccccccccccccckkkkkk.....",
  "kkkkkk..kkkkkkkkkkkkkkkkk...........",
  "...............kWk..................",
  "..............kWk...................",
  ".............kWk....................",
  "............kWk.....................",
  "...........kWk......................",
];

const RAY_IMAGE_HEX: Record<string, string> = {
  k: "#1FA85E", B: "#53B16D", L: "#E66852", N: "#94CEA8",
  W: "#72C38E", c: "#FEFEFE", d: "#65BB86", R: "#DDCC17",
  p: "#1A5A33", G: "#F4A29C", E: "#95985B", D: "#B3DDC6",
  Y: "#9FB728", O: "#AEC42B", m: "#266A48", a: "#9EC557",
  b: "#A86035", e: "#D9D552", f: "#A5744B", g: "#1B2D21",
};

// Rayquaza: an exact pixel trace of the reference model kit (ray_side.webp,
// downsampled + octree-quantized), kept whole and wagged as one body.
const RAY_IMAGE = [
  "...................................................................................................................dWN...................................",
  "...................................................................................................................Bkkd..................................",
  "...................................................................................................................NkkkB.................................",
  "....................................................................................................................kkkkB................................",
  "....................................................................................................................WkkkkB...............................",
  "....................................................................................................................DkkkkkB..............................",
  ".....................................................................................................................kkkkkkB.............................",
  ".....................................................................................................................NkkkkkkB............................",
  "......................................................................................................................kkkkkkkB...........................",
  "......................................................................................................................BkkkkkkkB..........................",
  "......................................................................................................................NkkkkkkkkW.........................",
  ".......................................................................................................................BkkkkkkkkW........................",
  ".........................................................................................................................BkkkkkkkN.......................",
  "..........................................................................................................................NWkkkkkkN......................",
  ".............................................................................................................................kkkkkkN.....................",
  "..............................................................................................................................kkkkkkD....................",
  "..............................................................................................................................NkkkkkBNNND................",
  "...........................................................................................................................NBkkkkkkkkBaEaaNNN............",
  "........................................................................................................................eEkkkkkkkkkkkkkkBBkkkBD..........",
  "......................................................................................................................DBRBkkkkkkkkkkkkkkkkkBBkBD.........",
  ".....................................................................................................................WkaRBBBBkkkkkkkkkkkkkkkkBBBN........",
  "....................................................................................................................dBdaakkkkkBBBBBkkkkkkkkmpkkBd........",
  "...................................................................................................................BBWBRakkkkkkBkkkkkkkkkkkkmgkkBd.......",
  ".............................GLL..................................................................................BdWBBREkkkkkkBkkkBBkkkkkkkBggmkBW......",
  "..........................G.LfBLG................................................................................BWWBBkRBkkkkkkBBkkfcfBBkkkkBmggmkcN.....",
  "........................GLbBkkkBL...............................................................................ddWBBkORkkkkkkkBBBkccccLffBkkBmcYpkBN....",
  ".....................GLbckkkkkkkfL.............................................................................NdWdBkORBkkkkkkBBBBckLLL..GLLEBBBBckBBN...",
  "....................GbkkkkkkkkkkkL.WD.........................................................................DBWdBkORkkkkkkkBBBBWkkBLLG....LLLEBWWBBBN..",
  ".....................fkkkkkkkkkkBBBkBNBkBBBBdWN...............................................................dWWBkORBkkkkkkBBBBcBdkkBcL....GLGLLLEBBdBD.",
  ".....................LkkkkkkkBBBBBBcpmcBkBBkkkkBWD...........................................................NdWBBaRBkkkkdcWBBBckN..kkEGL......GG.GGEBcd.",
  ".....................LkkkkBBBBBBBBBcppcBORRROBBBBkBN........................................................DBWdBBRBkkkkWcNBBBBkN...NkkLGL............NBW",
  "......................BkBBWdddBBBBBcppkRRYBYRROBBBBkd.......................................................WWWBBRYkkkkW.NBBBBk......dkBLLG............NW",
  "......................BWWWWddBBBBBBBkgRRkkkkkBROBBBBBBN....................................................NdWWBORkkkkd..NkBBB........kkEGLG.............",
  "....................NWNNWWdBBBkBELLfkgcRBkkkkkBRBBBBBBBN...................................................dWWdaRkkkkk................DkkfGG.............",
  "....................NNNWddBBBBELLLLLkgmBcckkkkBRRBBEBdBBN.................................................NdWdBRBkkkkD.................dkkLG.............",
  "...................BdWWdBBBELLLLLLLBkppkkY.YYYRcBRRRReBdBN................................................dWWBOOkkkkd...................kkBL.............",
  ".................NNBBWBBELLLLLLLfBkkkkgkkk....kkkRYkBeeadBN.............................................dBBBdcRBkkkk....................WkkfL............",
  "................NNNdcBELLLLLLfckkkkkkkd.NDNd.kkkkcBkkkaeBdB............................................NdWBBmYYkkBkW.....................dWN.............",
  "...............NNNWWmmELLLLfkkkkkkkkkkN.......dkkYYkkkkeedBW....................................GGGGGGGLBWWcpgpkkkk......................................",
  "..............NWNaeBcgpLfBkkkkkkkkkkcL..........dkRBkkkBeWdBD................................GLLfEEEEEEcBWWkgBBmpkN......................................",
  ".............NWeeaYccpgkkkkkkkkkkkkkk............dBRBkkBRNWBW................................GcBBkkkkkkkWBBppBBcBB.......................................",
  "............NWeeBkkYYkppkkkkkkkkkkkkkbG...........dBROcYRWWBd................................LEkBBBkkkkkBcpgpkBBBBd......................................",
  "...........NWeeBkkkYckkpBkkkkkkkkkkkkbG............BkYOROkBmcNW..............................LBkBkkkkkkkBBBmgpBBBkN......................................",
  "..........NWNeBkkkcckkkN..Gbkkkkkkk...G.............kkkpcpBBdBBG............................GLBkBkkkkkkBBBBWmgkBBB.......................................",
  ".........DWWaRkkkcckkd.......kkkkcbLG...............NmpmmkBNNBcEbbbbL.......................GLkkkkkkkckWdBdWBgkBkN.......................................",
  ".........WWWBRcccckkN.......Lk.bLG..................DBBkEcEWNBBBkkkkf........................EkkkkkkcpkBBkBdcpkBB........................................",
  "........NWWBYcYYckk.........G.......................kkkkLLLdWdBBkkkkcG......................LEkkkkkkppkkkkkBBpBBW........................................",
  ".......NdWBYRkkkkd................................LbkkkkLLLBWdBBkkkkBG......................LBkkkkkkpkmkkkkBkpBBN........................................",
  ".......dBaYRkkkkW...............................LbcpkkBkfLLBWWBBkkkkkL.....................GLkkkkkkkpkBmmBdBmmpk.........................................",
  "......NaRRRBkkkN...............................GbkkcckBkELLEWWBBBkkkkL.....................GfkkkkkkkpkBmgBcBBcmk.........................................",
  ".....DaRBkYckkW.................................bkkcckkkBLLEBdBBBkkkkb.....................LEkkkkkkkckBkpBWBBBBB.........................................",
  ".....WREkkYckd..................................LckcckkBBLLLBddBBkkkkcG....................LBkkkkkkkkkBkgkcBBBBN.........................................",
  "....DaekkkRk....................................LpkcckkBBLLLBddBBkkkkBG....................GLEkkkkkkkkBkgkcBBBBN.........................................",
  "....WeEkkcYk....................................GckcckkBkfLLBBdBBkkkkkL......................GLEkkkkkBBkgkBBBBBD..............NWWN.......................",
  "....deckYRkD.....................................bkccckBkELLEcdBBkkkkcL........................GLckkkBBkgkBBBBBD...........NWBBBd........................",
  "...NdERRYkd......................................bkccckBBBLcfBdBBkkcbLG..........................GLckBBmgkBBBBBBddWWNDD...WBBBBkN........................",
  "..NmBOOkkk.......................................LckcckkBBLcLBdBBBLG...............................bkBkmgkkBkkBBBBBBkkkkBBBBBkkk.........................",
  "..WkpbkkkN.......................................LcpppkBBBLLLBdBBB.................................kkBkppkkkkkkkkkBBBBBBBBBBdkkdN........................",
  "..BWkmppk........................................GLLLLBkBkEcbBWWkB.................................dkkkpgkkkkkkkkkkkkkkkBBBBBkkcN........................",
  ".NBBkkkkB..............................................WBkkppkkmd...................................NpmpgpppmN....DWdkkkkBWBBBBN.........................",
  ".NBELfkkD...............................................mmmcpmkmd...................................dkBkYckBkN..........NBkkkBBN.........................",
  ".WBLLEkd...............................................DBWBROcWcB...................................BkaRRRBBBN............BkkkkN.........................",
  ".BBLLBk.................................................BBYRORaBBD..................................kaRBkOYckD.............NNDD..........................",
  "DBELLBd.................................................BBRBkBeaBW.................................NBRBkkcRkk............................................",
  "NBELLkD.................................................WBRBkkEeBB.................................BaakkkERkB............................................",
  "NBLLEB..................................................NBRBkkBeaBN...........G.......G...........NBeEkkkOakW............................................",
  "WBLLBN...................................................BOYkkBaeBBD.........GcbbbbbbbcL..........BceBkkBRBkD............................................",
  "WBLLB....................................................WBRBkkaedBB.........LkkkkkkkkkL.........BBWeBkkROkB.............................................",
  "WELLd.....................................................kORBkOeWWBBD.......LkkkkkkkkkbG.......ddWdROBRRBkN.............................................",
  "WfLfN.....................................................WkORRRBdddBkN......bkkkkkkkkkbG.....NBdWdcBRRYBBB..............................................",
  "NLLED......................................................BkBYREBaaaBkBN...EckkkkkkkkkBfN..NdkaeeRORYkBBkN..............................................",
  ".LLB.......................................................NkkkBRRRRRRakkkdNkkkkkkkkkkkkkkNkkBeRaEEROkBBBd...............................................",
  "GcLN........................................................dkBkOOkBBaRaBkpkkkkkkkkkkkkkkkpkBRRBkkkOYkBBB................................................",
  "GLfN.........................................................BkkYOkBBkERBkpkkkkkkkkkkkkkBkpkaRBkBkkRBkBkD................................................",
  "DkkD..........................................................BkBRBkkBkOOkpkkkkBBBBBBBkkkBgkRBkkkkORBBkD.................................................",
  ".kk............................................................BkERBkkkBRkpBBkkkkkkkkkkBEBgcRBkkkORBkkD..................................................",
  ".kk.............................................................dkBRYcBYRbpfLLLLLLLLLLLLLBpcRRYOROBkB....................................................",
  ".NN..............................................................NkkYRRYkppfLLLLLLLLLLLLLBmpkcOYBkkW.....................................................",
  "...................................................................WkkkkkpkBLLLLLLLLLLLLEkkpkkkkkd.......................................................",
  ".....................................................................NkkkpkkkkkkkkkkkkkkkkkpkkkW.........................................................",
  "........................................................................NNkkkkkkkkkkkkkkkkkNDD...........................................................",
  "..........................................................................dkkkkkkkkkkkkkkkkN.............................................................",
  "............................................................................fkkkkkkkkkkkcG...............................................................",
  "............................................................................LckkkkkkkkkkbG...............................................................",
  "............................................................................GBkkkkkkkkkkb................................................................",
  "............................................................................GfkkkkkkkkkkL................................................................",
  ".............................................................................fkkkBBBBBkBL................................................................",
  ".............................................................................LLLLLLLLLLL.................................................................",
];

export type SerpentPiece = { rows: string[]; amp: number };
export type SerpentSprite = {
  name: string;
  palette: Record<string, string>;
  // "cross": swims straight across at a fixed height, alternating direction.
  // "prowl": slithers in from a side edge, dives, then wanders the open water.
  // Both stay in side profile the whole time.
  behavior: "cross" | "prowl";
  // A serpent is EITHER a segmented hand-art strip OR a single traced sprite.
  // `pieces` (tail -> head; amp is each piece's undulation amplitude in DESIGN
  // px, scaled up at render time) snakes via the per-piece wave. `image` is one
  // exact traced grid that wags as a whole body instead.
  pieces?: SerpentPiece[];
  image?: string[];
};

export const SERPENTS: SerpentSprite[] = [
  {
    name: "gyarados",
    palette: GY_HEX,
    behavior: "cross",
    pieces: [
      { rows: GS_FAN, amp: 26 },
      { rows: GS_BODY, amp: 22 },
      { rows: GS_FIN, amp: 18 },
      { rows: GS_BODY, amp: 15 },
      { rows: GS_BODY, amp: 12 },
      { rows: GS_FIN, amp: 9 },
      { rows: GS_BODY, amp: 7 },
      { rows: GS_BODY, amp: 5 },
      { rows: GS_FIN, amp: 3 },
      { rows: GS_HEAD, amp: 2 },
    ],
  },
  {
    name: "rayquaza",
    palette: RAY_IMAGE_HEX,
    behavior: "prowl",
    image: RAY_IMAGE,
  },
];
